### ISSUE TITLE
Addition of new units and new prohibition dates

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/cbrsservices_django#66]
List is here: https://docs.google.com/spreadsheets/d/11RmJpg9IN6hb-Oz8KU-NkcOLdbB1HIkupE4BhmoMiHA/edit?usp=sharing

**Comment by kjacobsen16** [comment]
@aaronstephenson I'm wondering if you could help me with this some time. I'm guessing we'll want to copy the prod DB to test, edit that, then push it back to prod, but I want to make sure I do it right.

**Comment by aaronstephenson** [comment]
This can be accomplished quickly using the API. Just write some POST requests to the production web services, `/systemunits/` and `/systemunitprohibitiondates/` respectively. Let me know if you'd like me to demonstrate this.

**Comment by kjacobsen16** [comment]
oh, yeah that's way easier. What would you recommend using to run those?

**Comment by aaronstephenson** [comment]
I use Insomnia, but other folks use Postman. I've also used plain old cURL. Any HTTP client would work.

**Comment by kjacobsen16** [comment]
Ok thanks, I'll use that!

**Comment by aaronstephenson** [comment]
It's been two years, I think KJ must have completed this.
