### ISSUE TITLE
Enable routing for commonly accessed routes

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/cbrsservices_django#72]
@aaronstephenson I believe we did this for NSS (https://test.streamstats.usgs.gov/nss-dev/).  Let me know if this is something I could set up, and how.

Right now you can only get to the test site by going to https://cbrstest.wim.usgs.gov/cbrsdms/, but there are several routes that would be good to be able to access it with:

- [x] https://cbrstest.wim.usgs.gov/cbrsdms/workbench -- this is most important since it's the default route on load, and if possible should let you access further out, like https://cbrstest.wim.usgs.gov/cbrsdms/workbench/3728 and https://cbrstest.wim.usgs.gov/cbrsdms/workbench/new

- [x] https://cbrstest.wim.usgs.gov/cbrsdms/mapdata

- [x] https://cbrstest.wim.usgs.gov/cbrsdms/reports -- the report views (e.g. `/casesbyunit`) get appended to this as well

- [x] https://cbrstest.wim.usgs.gov/cbrsdms/tags

- [x] https://cbrstest.wim.usgs.gov/cbrsdms/users

Edit 9/5
- [x] https://cbrstest.wim.usgs.gov/cbrsdms/login

Forgot to mention, this should be done to both https://cbrstest.wim.usgs.gov/cbrsdms/ and https://cbrs.wim.usgs.gov/cbrsdms/

**Comment by aaronstephenson** [comment]
I'm not sure what you mean. Could you phrase this differently?

**Comment by kjacobsen16** [comment]
I want someone to be able to use a url like https://cbrstest.wim.usgs.gov/cbrsdms/workbench to get to the test site. When you go to https://cbrstest.wim.usgs.gov/cbrsdms/ and login, it automatically takes you to https://cbrstest.wim.usgs.gov/cbrsdms/workbench, but if you try to refresh it, or try to navigate to the page just using that url, the page isn't found. It's an issue with all of the in-app routing.

Does that make more sense?

**Comment by aaronstephenson** [comment]
Yes thank you. This should be a simple Apache config change. I'll do that soon.

**Comment by aaronstephenson** [comment]
This was an easy change, once I found time. It just required a few changes:

1. Enable the Apache proxy module
    `a2enmod proxy`
2. Include the proxy and rewrite directives in the main Apache config (/etc/apache2/sites-avaialable/cbrstest-ssl.conf (or cbrsprod-ssl.conf))
```
    <Location /cbrsdms>
        ProxyPass !
        RewriteEngine On
        # If an existing asset or directory is requested go to it as it is
        RewriteCond %{REQUEST_FILENAME} -f [OR]
        RewriteCond %{REQUEST_FILENAME} -d
        RewriteRule ^ - [L]

        # If the requested resource doesn't exist, use index.html
        RewriteRule ^ /cbrsdms/index.html
    </Location>
```
3. Ensure the base href in the CBRSDMS index.html file is "cbrsdms"
    `<base href="/cbrsdms/">`
4. Restart the web server
    `service apache2 restart`

This is now implemented in both test and prod.
